// ====== EDIT HERE ======
// pdf: path of each day's one-pager inside the /pdf folder (upload it with this exact name).
const DAYS=[
{d:"Monday",date:"05 Oct 2026",pdf:"pdf/Day 01.pdf",
 sup:["Azim & Son U2 (Denim)","Noman Terry Towel Mills (Home Textile)"],lunch:"Azim & Son Unit-2",dinner:"Free evening / rest day",
 s:[["08:00–08:30","Meet up at Hotel Crowne Plaza Dhaka Airport","meet"],["08:30–10:00","Drive to Azim & Son Unit-2","travel"],["10:00–10:15","Refreshment break","meal"],["10:15–11:00","General discussion & company profile","meet"],["11:00–12:30","Factory round","factory"],["12:30–13:30","Lunch at Azim & Son Unit-2","meal"],["13:30–14:30","Drive to Noman Terry Towel Mills","travel"],["14:30–14:45","Refreshment break","meal"],["14:45–15:30","General discussion & company profile","meet"],["15:30–16:45","Factory round","factory"],["16:45–17:00","Refreshment break","meal"],["17:00–18:45","Drive to Hotel Crowne Plaza","travel"]]},
{d:"Tuesday",date:"06 Oct 2026",pdf:"pdf/Day 02.pdf",sup:["RGR Sweater Ltd. (Flat Knit)","Knit Plus Limited (Circular Knit)"],lunch:"Knit Plus Limited",dinner:"Hosted by Knit Plus Limited at Sheraton",
 s:[["07:45–08:00","Meet up at Hotel Crowne Plaza Airport","meet"],["08:00–09:30","Drive to RGR Sweater Ltd.","travel"],["09:30–09:45","Refreshment break","meal"],["09:45–11:30","General discussion & company profile","meet"],["11:30–12:30","Factory round","factory"],["12:30–12:45","Refreshment break & depart RGR","meal"],["12:45–14:15","Drive to Knit Plus Limited","travel"],["14:15–14:45","Lunch at Knit Plus Limited","meal"],["14:45–15:30","General discussion & company profile","meet"],["15:30–16:30","Factory round","factory"],["16:30–16:45","Refreshment break & depart Knit Plus Limited","meal"],["16:45–18:30","Drive to dinner point","travel"],["18:30–20:30","Dinner","meal"],["20:30–21:30","Drive to Hotel Crowne Plaza","travel"]]},
{d:"Wednesday",date:"07 Oct 2026",pdf:"pdf/Day 03.pdf",sup:["RBD Fibers Limited (Recycler to Recycler)","Oi Dhaka Office"],lunch:"RBD Fibers Limited",dinner:"Team dinner · Thai Emerald, Uttara",
 s:[["08:00–08:15","Meet up at Hotel Crowne Plaza Airport","meet"],["08:15–10:00","Drive to RBD Fibers Limited","travel"],["10:00–10:15","Refreshment break","meal"],["10:15–11:00","General discussion & company profile","meet"],["11:00–12:30","Factory round","factory"],["12:30–13:15","Lunch at RBD Fibers Limited","meal"],["13:15–14:30","Drive to Oi office","travel"],["14:30–14:45","Refreshment break","meal"],["14:45–15:00","Welcome meeting with Head of Merchandise, Material & Compliance","meet"],["15:00–15:30","Oi office round","meet"],["15:30–18:00","Individual discussion sessions, based on visitors' needs","meet"],["18:00–18:30","Drive to dinner point","travel"],["18:30–20:30","Team dinner","meal"],["20:30–21:00","Drive to Hotel Crowne Plaza","travel"]]},
{d:"Thursday",date:"08 Oct 2026",pdf:"pdf/Day 04.pdf",sup:["Graphics Textiles Ltd. (Circular Knit)","Pakiza Knit Composite Ltd (Circular Knit)"],lunch:"Graphics Textiles Ltd.",dinner:"Hosted by Pakiza at The Westin Dhaka",
 s:[["07:30–07:45","Meet up at Hotel Crowne Plaza Airport","meet"],["07:45–09:30","Drive to Graphics Textiles Ltd.","travel"],["09:30–09:45","Refreshment break","meal"],["09:45–11:30","General discussion & company profile","meet"],["11:30–12:30","Factory round","factory"],["12:30–13:30","Lunch at Graphics Textiles Ltd.","meal"],["13:30–14:30","Drive to Pakiza Knit Composite Ltd","travel"],["14:30–14:45","Refreshment break","meal"],["14:45–15:30","General discussion & company profile","meet"],["15:30–16:30","Factory round","factory"],["16:30–16:45","Refreshment break","meal"],["16:45–18:45","Drive to dinner point","travel"],["18:45–20:30","Dinner","meal"],["20:30–21:30","Drive to Hotel Crowne Plaza","travel"]]},
{d:"Friday",date:"09 Oct 2026",pdf:"pdf/Day 05.pdf",sup:["Chittagong Denim Mills Ltd. (Woven Mill)","Mayer Achol (NGO)"],lunch:"Chittagong Denim Mills Ltd.",dinner:"Hosted by Chittagong Denim Mills Ltd. at Le Meridien Dhaka",
 s:[["08:15–08:30","Meet up at Hotel Crowne Plaza Airport","meet"],["08:30–10:00","Drive to Chittagong Denim Mills Ltd.","travel"],["10:30–10:45","Refreshment break","meal"],["10:45–11:30","General discussion & company profile","meet"],["11:30–12:45","Factory round","factory"],["12:45–13:45","Lunch at Chittagong Denim Mills Ltd.","meal"],["13:20–13:45","Prayer break","meet"],["13:45–15:30","Drive to Mayer Achol","travel"],["15:30–15:45","Refreshment break","meal"],["15:45–17:30","Visit at Mayer Achol","factory"],["17:30–18:30","Drive to dinner point","travel"],["18:30–20:30","Dinner","meal"],["20:30–21:30","Drive to Hotel Crowne Plaza","travel"]]}];
const WX=[["MON 05","32° / 25°","Mostly sunny"],["TUE 06","32° / 24°","Mostly sunny"],["WED 07","32° / 24°","Sunny"],["THU 08","32° / 24°","Sunny periods"],["FRI 09","32° / 24°","Sunny spells"]];
const CON=[["Mehtap Mir","Head of People Operations & Workplace","+8801322905275","Emergency Contact"],["Md. Saiful Islam","Corporate Responsibility Lead, Climate","+8801322905272","Support Contact"]];
// ====== APP ======
const $=s=>document.querySelector(s),ini=n=>n.split(" ").map(w=>w[0]).slice(0,2).join("");
const KINDS={factory:"Factory / site",travel:"Travel",meal:"Break / meal",meet:"Meeting"};
$("#tabs").innerHTML=DAYS.map((x,i)=>`<button data-i="${i}"><b>Day ${String(i+1).padStart(2,"0")}</b><span>${x.d.slice(0,3)}, ${x.date.slice(0,6)}</span></button>`).join("");
$("#cgrid").innerHTML=CON.map(c=>`<div class="p"><span class="tag">${c[3]}</span><b>${c[0]}</b><small>${c[1]}</small><br><a href="tel:${c[2]}">${c[2]}</a></div>`).join("");
async function show(i){
  i=Math.max(0,Math.min(DAYS.length-1,i|0));const x=DAYS[i],u=encodeURI(x.pdf),w=WX[i];
  $("#wx").innerHTML=`<div><span>${x.d}, ${x.date.slice(0,6)}</span><b>${w[1]}</b><span>${w[2]}</span></div>`;
  document.querySelectorAll("#tabs button").forEach((b,k)=>{b.classList.toggle("on",k==i);b.setAttribute("aria-pressed",k==i)});
  let ok=true;if(location.protocol.startsWith("http")){try{ok=(await fetch(u,{method:"HEAD"})).ok}catch(e){ok=false}}
  $("#day").innerHTML=`<div class="dh"><div><p>Day ${i+1}</p><h2>${x.d}, ${x.date}</h2></div></div>
  <div class="chips">${x.sup.map(s=>`<span class="chip"><svg class="pin" viewBox="0 0 24 24" aria-hidden="true"><path fill="#EA4335" d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></svg> ${s}</span>`).join("")}</div>
  <div class="cols"><div><div class="legend">${Object.entries(KINDS).map(([k,v])=>`<span><i style="background:${{factory:"var(--ac)",travel:"#2b8cff",meal:"#f59e0b",meet:"#a855f7"}[k]}"></i>${v}</span>`).join("")}</div>
  <ul class="tl">${x.s.map(r=>`<li data-t="${r[2]}"><time>${r[0]}</time><span class="${r[2]=="factory"?"f":""}">${r[1]}</span></li>`).join("")}</ul></div>
  <div class="info"><div class="box"><h3>Lunch</h3><p>${x.lunch}</p></div><div class="box"><h3>Dinner</h3><p>${x.dinner}</p></div>
  <div class="box"><h3>Transport</h3><p>Dedicated cars from Hotel Crowne Plaza Dhaka Airport.</p></div></div></div>
  <div class="pdf"><h3>Visiting Plant Details</h3>${ok?`<div class="btns"><a class="btn" href="${u}" target="_blank" rel="noopener">Open PDF ↗</a><a class="btn ghost" href="${u}" download>Download</a></div><iframe class="frame" src="${u}#view=FitH" title="Day ${i+1} one-pager"></iframe>`:`<div class="na">📄 The Day ${i+1} one-pager will be available here soon.</div>`}</div>`;
  history.replaceState(null,"","#day"+(i+1));
}
$("#tabs").onclick=e=>{const b=e.target.closest("button");if(b)show(+b.dataset.i).then(()=>$("#day").scrollIntoView({behavior:"smooth",block:"start"}))};
const th=localStorage.getItem("theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");
document.documentElement.dataset.theme=th;
$("#theme").onclick=()=>{const n=document.documentElement.dataset.theme=="dark"?"light":"dark";document.documentElement.dataset.theme=n;try{localStorage.setItem("theme",n)}catch(e){}};
show((location.hash.match(/day(\d)/)||[0,1])[1]-1);
